name: ucg_interactable_svg
description: Flutter package to interact with different regions of an SVG.
version: 1.0.25
homepage: https://github.com/ugurgoker/ucg_interactable_svg

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  svg_path_parser: ^1.1.2
  xml: ^6.5.0